### DISCUSSION TITLE
Easy knitr render on GitHub

### DISCUSSION THREAD

**Discussion by sr320** [RobertsLab/resources#1200] [Show and tell]
You probably already knew this.. but frustrated with a lack of easy visualization of Rmd in GitHub....

simply

```
title: "01-data-explore"
output:
  md_document:
    variant: markdown_github
```

eg https://github.com/sr320/clam-development/blob/main/code/01-data-explore.md

(yes the first plot I have made in three months... I will post urls 😃 )
