### ISSUE TITLE
Navbar icons not showing in Quarto website

### ISSUE THREAD

**Issue by kubu4** [RobertsLab/resources#1705]
Managed to get my test Quarto site up and running:

https://kubu4.github.io/quarto-testing/

I grabbed the `_quarto.yml` from the [lab website repo](https://github.com/RobertsLab/lab-website/blob/02f8a1b154c22a142188a7c518c2841371c8d17f/_quarto.yml) as simple means of duplicating things. I did remove the sidebar and I changed the theme. But, I don't think those should impact the navigation bar icons.

Here's my [`_quarto.yml`](https://github.com/kubu4/quarto-testing/blob/main/_quarto.yml):

```
project:
  type: website
  output-dir: docs


website:
  title: "robertslab.info"
  navbar:
    background: primary
    search: true
    # left:
    #   - text: "What"
    #     file: index.qmd
    #   - text: "Who"  
    #     file: publications.qmd
    #   - text: "How"  
    #     file: posts.qmd
    #  
    tools:
      - icon: hdd-network
        menu:
          - text: raven
            url:  http://raven.fish.washington.edu:8787
          - text: gannet
            url:  https://gannet.fish.washington.edu
    
      - icon: journal-code
        menu:
          - text: sam
            url:  https://robertslab.github.io/sams-notebook/
          - text: steven
            url:  https://sr320.github.io
      - icon: github
        menu:
          - text: Lab Organization
            url:  https://github.com/RobertsLab
          - text: Edit Roberts Lab website
            url: https://github.com/RobertsLab/lab-website
      - icon: calendar-week
        href: https://calendar.google.com/calendar/embed?src=mrc305@gmail.com&ctz=America/Vancouver
       


    
format:
  html:
    theme: darkly
    css: styles.css
    toc: true

editor: visual
```

Anyone have any suggestions on how to get the icons to show up?
