### ISSUE TITLE
RSS feed or some other way to allow for subscribers to lab notebooks? 

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#1804]

**Comment by grace-ac** [comment]
i know my old notebook I used Disqus

**Comment by grace-ac** [comment]
ok.. turns out i already have disqus set up for my current notebook, too! but it looks like only for it to provide updates to subscribers is if they create a disqus account

**Comment by kubu4** [comment]
If you're using Quarto notebook, add `feed: true` to your notebook _site_ `index.qmd`. This is what mine looks like:

```
---
title: "University of Washington - SAFS - Roberts Lab"
listing:
  contents: posts
  sort: "date desc"
  type: default
  categories: true
  sort-ui: false
  filter-ui: false
  feed: true
page-layout: full
title-block-banner: true
css: styles.css
---
```

Then, you can also a link to the RSS feed, with an icon on your homepage by adding the following to your `_quarto.yml`:

```
-icon: rss
 href: index.xml
```

Here's what mine looks like:

```
project:
  type: website
  output-dir: docs


website:
  title: "Sam's Notebook"
  site-url: https://robertslab.github.io/sams-notebook
  repo-url: https://github.com/RobertsLab/sams-notebook
  favicon: /images/favicon.ico
  page-navigation: true
  google-analytics: "G-7483T61T11"
execute:
  freeze: auto

  navbar:
    background: primary
    search: true
    # left:
    #   - text: "What"
    #     file: index.qmd
    #   - text: "Who"  
    #     file: publications.qmd
    #   - text: "How"  
    #     file: posts.qmd
    #  
    right:
      - icon: hdd-network
        menu:
          - text: Rstudio Server - Raven
            href:  http://raven.fish.washington.edu:8787
            target: _blank
          - text: My Gannet Directory
            url:  https://gannet.fish.washington.edu/Atumefaciens/
            target: _blank
    
      - icon: journal-code
        menu:
          - text: Steven's Notebook
            url:  https://sr320.github.io
            target: _blank
          - text: Kathleen's Notebook
            url: https://shedurkin.github.io/Roberts-LabNotebook/
            target: _blank
          - text: Megan's Notebook
            url: https://meganewing.github.io/mewing-notebook/
            target: _blank
      - icon: github
        menu:
          - text: Notebook repo
            url: https://github.com/RobertsLab/sams-notebook
            target: _blank
          - text: Lab Organization (GitHub)
            url:  https://github.com/RobertsLab
            target: _blank
          - text: Edit Roberts Lab website
            url: https://github.com/RobertsLab/lab-website
            target: _blank
      - icon: calendar-week
        href: https://calendar.google.com/calendar/embed?src=mrc305@gmail.com&ctz=America/Vancouver
        target: _blank
      - icon: rss
        href: index.xml
       


    
format:
  html:
    theme: darkly
    css: styles.css
    toc: true
    page-layout: full
    code-background: true
    code-copy: true
    code-fold: true

editor: visual
```
